### ISSUE TITLE
Question:  Queue Menu Item in Carrier View

### ISSUE THREAD

**Issue by Angela-MLI** [ApexaCorp/feedback-portal#118]
Queue Menu Option was not discussed during training - is there a separate training session being scheduled to go over what this view is?

**Comment by KelsiElshaw** [comment]
Hi Angela,

While part of this was built and released into the training environment, it is not complete and has not been validated (so we didn't go over it in training).
When we meet for our second training gather round we will definitely plan to go over this feature.

Best,
Kelsi
