### ISSUE TITLE
Question: Unable to select 'Contract Document' checkbox

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#12]
Hello,

I created documents and could not check the 'Contract Document' checkbox.
I am unable to add the documents to a Package:

![2015-09-15 12-35-48 pm](https://cloud.githubusercontent.com/assets/14218407/9883259/1e5441f8-5ba7-11e5-825d-fb3d56eba028.png)

![2015-09-15 12-40-27 pm](https://cloud.githubusercontent.com/assets/14218407/9883271/281e8b8a-5ba7-11e5-877b-b9da62b28471.png)

There must be something I am forgetting, any help would be appreciated.

**Comment by mikebrown0** [comment]
A contract must be a fillable document.  This is a requirement for digital signatures to work.  As per my suggesting in issue #11, just upload a placeholder document until the contract builder is available.
