### ISSUE TITLE
Uploading Documents: user is logged out intermittently

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#13]
I was unable to replicate this issue but it did occur on 3 different users on separate screens, the commonalities are;

1. Carrier Portal: we click on New Document, select type and browse for file to upload, Pause time is minimimal (under 30 seconds) when file is selected we are brought back to the log-in screen.

2. Advisor Portal: same as above but occurs when uploading a license document.

It is always hard to debug intermittent issues, but it might be worth while to look into this.

**Comment by mikebrown0** [comment]
The version that is currently deployed may log users out after 30 minutes regardless of activity.  I can't remember if this was fixed before or after the specific version that was deployed.  Milestone 3 will be deployed in the next 24-48 hours and definitely has a fix for the issue I'm aware of.  I'll leave this issue open for now, please let me know if you get reports of the issue after the next version is deployed.
