### ISSUE TITLE
BUG:  Unable to log into UAT (MGA or Carrier)

### ISSUE THREAD

**Issue by Angela-MLI** [ApexaCorp/feedback-portal#138]
Logging into https://uportal.apexa.ca or https://uintrust.apexa.ca - cannot log in using credentials provided.

**Comment by mikebrown0** [comment]
Hi Angela,

I apologize for the late reply.  I just tried logging in using the credentials we issued and all of them appear to work.  Please let me know if this issue persists.

Mike
