### ISSUE TITLE
Advisor Wizard: E&O

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#14]
Observations:

1. The Advisor is asked for E&O Termination Date during the initial account setup, we think it might confuse the Advisor as it would never be used at this point, whereas during editing it would be used when changing E&O carriers.

2. The E&O renewal date should be a required field.

3. E&O is missing the upload functionality.

**Comment by mikebrown0** [comment]
1 & 3 are fixed in Milestone 3.
2 will be fixed in Milestone 4.
