### ISSUE TITLE
Question: Token and IF statement used within FOREACH

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#147]
I need to list the associates within Personal.Businesses[0].Associates where the associates are shareholders.

I tried the following but returns "undefined";

* @foreach(var associate in Personal.Businesses[0].Associates.*IsShareholder*) {}

* @foreach(var associate in Personal.Businesses[0].Associates) {
@if(associate.IsShareholder){
}
}

Would you have any suggestions?

I also tested a sinple token on 0.5.4 and it returns the same error:

![2015-11-13 11-30-03 am](https://cloud.githubusercontent.com/assets/14218407/11151265/20bb1846-89fa-11e5-8121-bdf44c9075d0.png)

Frank

**Comment by frank-slf** [comment]
It appears that the 30 minute auto log-out did not redirect me to the log-in screen, it left me in the session without access, thereby generating the bogus error messages.

**Comment by mikebrown0** [comment]
Hi Frank,

This should be resolved by #149.  Let me know if the issue persists.

Mike
