### ISSUE TITLE
BUG: Assets modifications dates do not update as expected

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#150]
I updated 'Agreement' on 2015-11-16 09:49, expected Modification date of 2015-11-16:

![2015-11-16 9-47-55 am](https://cloud.githubusercontent.com/assets/14218407/11184740/47cb55be-8c47-11e5-9757-3d8cd7e9556a.png)

**Comment by mikebrown0** [comment]
Hi Frank,

This has been fixed and will be released later tonight.  It's worth mentioning that the modified date is tied to a change in the section content and not the title or description (since those do not create a new revision).

Mike
