### ISSUE TITLE
Advisor Wizard Step 11: Insurance History

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#16]
Observation:

Insurance History - LOB; if you choose LAS field, Life Total Premium is required.

What is this field used for?
Should this be a required field?

Advisors may be reluctant to provide this information.

**Comment by mikebrown0** [comment]
This is from the ASQ:
![image](https://cloud.githubusercontent.com/assets/1004965/10021401/cf6172ea-6115-11e5-8d48-cf4430f2b659.png)

When we asked how this form is used, the answer we got was that advisors would be instructed to put *something* in this field even if it was a best guess.  Based on that, it became a required field in APEXA so they would need to put *something*.

If this is not the case, please let us know.  It may be worth a discussion with the group as a whole.

**Comment by frank-slf** [comment]
I think the '**approximate total premium**' field should be optional in line with the ASQ's note (if known(.

Frank
