### ISSUE TITLE
Advisor Portal: Profile/Education

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#18]
Once the wizard has been competed, the Profile/Education comes up as data entry instead of a list, actually it appears there is no list view.

**Comment by mikebrown0** [comment]
That area in particular (along with the Personal Information and Compliance page) was built to mirror the ASQ form rather that the list metaphors we've developed.
![image](https://cloud.githubusercontent.com/assets/1004965/10021927/558adec2-6118-11e5-839b-7a2d15bdab19.png)
It may be worth revisiting those 3 pages if there is time near the end of the project.  I'll leave this item open for a while to see if others have comments about it.
