### ISSUE TITLE
Carrier: Issue on last step of "package setup" wizard

### ISSUE THREAD

**Issue by KelsiElshaw** [ApexaCorp/feedback-portal#19]
On the final step of the package set up wizard, "Request for Documents." I have selected the "Add" button and the system hangs.
I am able to progress backward using the "Previous" button, but then when I progress forward again to the Request for Documents page and select the "Add" button the issue is still present.

When I came back to the screen to attempt a screenshot for this issue log, I received the following error (my connectivity was not lost) 
![image](https://cloud.githubusercontent.com/assets/14805347/10075971/c98d9c80-62a6-11e5-9b6f-d13ecc198434.png)

When I refreshed, my work was lost and package was not saved.

**Comment by KelsiElshaw** [comment]
Please note, if I select "Finish" (and do not attempt to add any requests for documents), the package is saved successfully.

**Comment by mikebrown0** [comment]
The fix for this will be in the Milestone 4 build.
