### ISSUE TITLE
InTrust: Updating Contractor Address

### ISSUE THREAD

**Issue by KelsiElshaw** [ApexaCorp/feedback-portal#20]
I am attempting to add an address for a contractor (Kelsi Van Kruistum is the contractor record).
I am able to open a new address record and fill in all the information. I get the green check mark for each of the fields indicating a validated entry. When I select "Save," however, nothing happens and I remain on the screen.

**Comment by mikebrown0** [comment]
The fix for this will be in the Milestone 4 build.
