### ISSUE TITLE
French Invite email

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#3]
French email invite needs corrections:
![2015-09-10 9-17-07 am](https://cloud.githubusercontent.com/assets/14218407/9792956/fb635cf0-57b0-11e5-91e4-cd4edbe1f179.png)

**Comment by frank-slf** [comment]
When an Advisor receives a french invite, the token link should display the French Create Account page:

![2015-09-10 9-48-06 am](https://cloud.githubusercontent.com/assets/14218407/9790567/bd3659b6-57a4-11e5-9f35-1c0cea200fe5.png)


When link to french is clicked (APEXA Portail Conseiller, offert en français) it does not ,a french log-in page comes up instead of the first log-in page:

![2015-09-10 9-59-09 am](https://cloud.githubusercontent.com/assets/14218407/9790572/c495bed6-57a4-11e5-92aa-55ae75f0eb8c.png)


If we click the back button or click on the emailed link again, then we get the french first log-in page:
* suggested french corrections included: " Veuillez, s'il vous plait, nous fournir vos informations d'enregistrement. Vous devriez avoir reçu une invitation jeton par email à partir de votre AGP ou Assureur. Vous avez besoin de cette information pour compléter le processus d'inscription.
":

![2015-09-10 10-00-02 am](https://cloud.githubusercontent.com/assets/14218407/9790593/e3b5665e-57a4-11e5-9553-220e63aa74f8.png)

**Comment by mikebrown0** [comment]
Thank you.  These changes are being made.  We'll try to get them in next week's release.
