### ISSUE TITLE
French First Log In

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#4]
When an Advisor receives a french invite, the token link should display the French Create Account page, we land on an English first log-in page instead:

![2015-09-10 9-48-06 am](https://cloud.githubusercontent.com/assets/14218407/9790673/5d41bb08-57a5-11e5-88f8-bc21c2580942.png)

When link to french is clicked (APEXA Portail Conseiller, offert en français), a french log-in page comes up instead of the first log-in page:

![2015-09-10 9-59-09 am](https://cloud.githubusercontent.com/assets/14218407/9790683/62f3b740-57a5-11e5-88f2-dd39286468b5.png)

If we click the back button or click on the emailed link again, then we get the french first log-in page:
* suggested french corrections included: "Veuillez, s'il vous plait, nous fournir vos informations d'enregistrement. Vous devriez avoir reçu un code d'enregistrement envoyé par email de la part de votre AGP ou Assureur. Vous avez besoin de cette information pour compléter le processus d'inscription.":

![2015-09-10 10-00-02 am](https://cloud.githubusercontent.com/assets/14218407/9792973/120e794e-57b1-11e5-90b1-7488046922a7.png)

**Comment by frank-slf** [comment]
JFYI:
Bottom left should read "Propulsé par BlueSun Inc"

**Comment by mikebrown0** [comment]
Thank you.  These changes are being made.  We'll try to get them in next week's release.
