### ISSUE TITLE
Search Results not working

### ISSUE THREAD

**Issue by Charryse-CL** [ApexaCorp/feedback-portal#50]
Search results are showing everything rather than filtering on the criteria entered. Note, tags are not appearing for Packages created. Will we be able to search by tags on Packages?

**Comment by mikebrown0** [comment]
At the moment the search criteria screens are still from the prototype and are not connected to anything.  The search functionality is scheduled to be available with the Milestone 5 release (November 2).  Once available, you'll be able to search on tags and lots of other criteria.
