### ISSUE TITLE
Packages: Questions - Custom Field

### ISSUE THREAD

**Issue by Charryse-CL** [ApexaCorp/feedback-portal#51]
In Step 4 (Questions) of the Package set-up, what should be entered in the "Custom Field" section? There is no mention of this in the Partner Guide: Milestone 2 document.

**Comment by mikebrown0** [comment]
That field is more IT related than anything else.  It is the KEY that is used to find this specific question in the contract builder and the CITS feed.  The Milestone 4.5 documentation will likely have a reference to it when that is released.  It is essentially a unique identifier so you can programatically find the associated question and answer without needing to worry about what language the question was asked in.
