### ISSUE TITLE
Attestation

### ISSUE THREAD

**Issue by Charryse-CL** [ApexaCorp/feedback-portal#54]
What notifications will we get from attestation? If an advisor goes through attestation and there is no changes to the Advisor's profile, will we still get notified? Can we only get notified of the changes?

**Comment by mikebrown0** [comment]
In the version of notifications that will be available next week, you can get a list of advisors that have an upcoming attestation or have not completed their attestation.  Once they attest, the advisor would disappear from the list.  If you've setup notifications on for something like and address change, then those notifications would get triggered, but there is currently no explicit "completed attestation" notification.

**Comment by Charryse-CL** [comment]
Thanks Mike! We would not need to be notified if there are no changes to the Advisor's information after attestation. We are only interested when there are changes.
