### ISSUE TITLE
SECURITY: Roles should have a checkbox for APEXA Settings access

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#56]
Most roles should not be allowed to access the APEXA Settings area, we will only have 1 or 2 roles that will should have access to Settings.

Could you please address this at the next Review?

![2015-10-26 2-09-17 pm](https://cloud.githubusercontent.com/assets/14218407/10737954/60394d02-7beb-11e5-82b3-c36109b91d0b.png)

**Comment by mikebrown0** [comment]
This is currently planned as one of the permissions that will be included in Milestone 5.
