### ISSUE TITLE
CITS Connection Error

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#57]
Hello,

We are testing the connection to the CITS web service with this URL:

*To test this service, you will need to create a client and use it to call the service. You can do this using the svcutil.exe tool from the command line with the following syntax:
 
svcutil.exe https://tapi.apexa.ca/v1/CITSService.svc?wsdl
You can also access the service description as a single file:
 
https://tapi.apexa.ca/v1/CITSService.svc?singleWsdl
This will generate a configuration file and a code file that contains the client class. Add the two files to your client application and use the generated client class to call the Service.*
 
However we keep receiving this error:

![2015-10-26 2-36-13 pm](https://cloud.githubusercontent.com/assets/14218407/10738725/17ea89f4-7bef-11e5-80f3-e8e2da53655f.png)

Also the user credentails we were given (username/password) does not match what is requested:

![2015-10-26 2-36-57 pm](https://cloud.githubusercontent.com/assets/14218407/10738727/1dc7083e-7bef-11e5-9229-b38753751704.png)

Any help would be appreciated.

Thanks

**Comment by mikebrown0** [comment]
Hi Frank,

The command you posted for svcutil.exe works fine:
![image](https://cloud.githubusercontent.com/assets/1004965/10800478/5a596036-7d88-11e5-8edf-24b1feb4a3ed.png)

It looks like you're using a Java tool of some kind based on the screenshot.  I'm not sure what tool it is or how it works, but it looks like it's set for NTLM authentication when the API uses basic authentication (just username and password, no domain).  These credentials need to be passed in the SOAP header.

We've included a .NET example of how to do this, but there should be a way to do it in any language.  I'm not 100% sure this is the exact solution you need, but this will hopefully get you pointed in the right direction: http://stackoverflow.com/questions/7071366/java-web-service-client-basic-authentication

Mike

**Comment by frank-slf** [comment]
Hello,

The authentication error has been resolved, than you for the materials.

We still have issues with the first error: 

![2015-11-03 2-21-45 pm](https://cloud.githubusercontent.com/assets/14218407/10918965/49f04d10-8236-11e5-8a00-3734a62f32a4.png)

Can we connect out IT resources on a conf call or via email to ensure we have what is needed to connect and retrieve data ?

Please advise,

Frank

**Comment by mikebrown0** [comment]
Hi Frank,

I'll send you the details for one of our resources shortly.

Mike

**Comment by mikebrown0** [comment]
Hi Frank,

I sent you an email, but I'm not sure if I have the right email address.  If that email didn't find you, please email myself or someone from APEXA directly and we'll get the right person in touch with you.

Mike

**Comment by frank-slf** [comment]
Hi Mike,

Can we schedule 2015-11-26 @ 10:00 Am?

Counter if not available or confirm and I will send meeting details.

Thanks,

Frank

**Comment by frank-slf** [comment]
Hi Mike,

The errors we are experiencing may be due to wsdl services blocked by the SLF Firewall, I have raised ticket with our IT  Security department to investigate further.

Frank
