### ISSUE TITLE
Advisor Search

### ISSUE THREAD

**Issue by Charryse-CL** [ApexaCorp/feedback-portal#58]
Hi, 

I noticed that you still cannot search for an Advisor using the code we (the carrier) assigns to them. Only the APEXA ID is available. Will this be available by UAT?

We would also want to be able to search by the MGA Branch code. 

Thanks.

**Comment by mikebrown0** [comment]
The search screens are currently from the prototype and are not functional.  The real search screens will be available in Milestone 5 and will include things like searching by contract codes and the MGA.
