### ISSUE TITLE
Question: For advisors that are already contracted with MGA/Carrier Is the Carrier access to these advisors automatic based on the In Trust feeds?

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#60]
For advisors that are already contracted with MGA/Carrier, will they be automatically be set-up so that the Carrier can access information updates such as licenses etc..?

**Comment by mikebrown0** [comment]
The relationships that are represented in In-Trust will be imported into APEXA when the advisor is onboarded.  That means you'll have a live connection to each of those advisors that you will receive updates from.

**Comment by frank-slf** [comment]
Hello,

I am having a hard time tracking this on the any of the Process Flows and Requirement Documents, do we have any details on how this works?

Frank
