### ISSUE TITLE
Question: Is SLF Carrier 5 scheduled for roll out on 2016-01-25?

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#61]
Is SLF Carrier 5? 
If so, can you confirm we are scheduled for roll out on 2016-01-25?

**Comment by KelsiElshaw** [comment]
Hi Frank,

Yes I can confirm that SLF is scheduled to Go Live on January 25th.

K.

Kelsi Elshaw, MA, PMP | Project Manager/Business Analyst
P: +1 647.800.8665  |  C: +1 905.510.8024
www.apexa.ca<http://www.apexa.ca/>
