### ISSUE TITLE
HUB.APEXA.CA: Can we confirm that the data sent via hub.apexa.ca is encrypted?

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#62]
Is the data sent via hub.apexa.ca encrypted?

![2015-10-27 3-18-49 pm](https://cloud.githubusercontent.com/assets/14218407/10769761/1ae943c8-7cbe-11e5-8d5c-065e73ab16e3.png)

If not can you suggest an encrytion method?

Frank

**Comment by mikebrown0** [comment]
Hi Frank,

Everything is encrypted, both during transport and at rest, so there should be no need to encrypt the file before sending it.  If you need more details let me know and I can forward you information on the security appliance that manages this.

- Mike

**Comment by frank-slf** [comment]
HI Mike, 

Please provide any encryption details you have for us to get the hub.aplexa.ca enabled.

Thanks.

Frank
re13@sunlife.com

**Comment by mikebrown0** [comment]
Hi Frank,

The here is the information APEXA IT has provided for me to pass on:

- [File Transfer Data Sheet](http://www.ipswitchft.com/getattachment/25d640d1-941b-4ccb-945c-d091747a65e9/MOVEit-File-Transfer-%28DMZ%29)
- [Additional Data Sheets](http://www.ipswitchft.com/resources/data-sheets)

If you need more information, I'll have to get you connected with APEXA IT directly to answer any additional questions you may have.

Mike
