### ISSUE TITLE
DOCUMENTS: Unusual Page Size (A4?)

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#63]
The page size should allow the advisor to print to a standard page size of 8.5 x 11.

Current page size is  8.26 X 11.69.

![2015-10-28 1-11-25 pm](https://cloud.githubusercontent.com/assets/14218407/10796694/ab057906-7d75-11e5-9c9d-30c26d094478.png)

**Comment by mikebrown0** [comment]
The page size has been changed to 8.5 x 11.  You'll see this in the Milestone 5 deployment.
