### ISSUE TITLE
Question: Partner Portal Security/Users 'Enable Lockout' checkbox

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#9]
When the 'Enable Lockout' is unselected the user gets locked out, when selected, the user is able to log-in.

![2015-09-11 12-46-38 pm](https://cloud.githubusercontent.com/assets/14218407/9820701/9342ff9e-5883-11e5-8ea8-2eb2a801f5f9.png)

It appears counter intuitive, does it make sense?

Frank

**Comment by mikebrown0** [comment]
I agree this is confusing.  The lockout feature has been problematic based on the security model that is being used; this is actually the second iteration of it.  This area is going to be getting a new version of this (likely for Milestone 4) when we do the work to enforce all of the security settings.

I'll leave this item open until that work has been completed.
